<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- mtbc1 Sensor Models based on Turtlebot4 -->
  <!-- 
  <xacro:include filename="$(find mtbc1_description)/urdf/sensors/imu.urdf.xacro" />  -->
  <xacro:include filename="$(find mtbc1_description)/urdf/sensors/oakd.urdf.xacro" />
  <xacro:include filename="$(find mtbc1_description)/urdf/sensors/camera_bracket.urdf.xacro" />
  <xacro:include filename="$(find mtbc1_description)/urdf/sensors/rplidar.urdf.xacro" />
  
  <!-- linorobot2 sensor names -->
  <!--
  <xacro:include filename="$(find mtbc1_description)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find mtbc1_description)/urdf/sensors/generic_laser.urdf.xacro" />
  <xacro:include filename="$(find mtbc1_description)/urdf/sensors/depth_sensor.urdf.xacro" />
  -->
  <xacro:include filename="$(find mtbc1_description)/urdf/sensors/sensors_shelf.urdf.xacro" />

  <!-- TB4 sensors definitions from turtlebot4.urdf.xacro,revised for turtlebot createC1 with gazebo parameters deleted-->
  
  <!-- Mechanical properties -->
  <xacro:property name="rplidar_x_offset"              value="${0*cm2m}"/>
  <xacro:property name="rplidar_y_offset"              value="${0*cm2m}"/>
  <xacro:property name="rplidar_z_offset"              value="${4.7*cm2m}"/>

  <xacro:property name="camera_mount_x_offset"         value="${-9*cm2m}"/>
  <xacro:property name="camera_mount_y_offset"         value="${0*cm2m}"/>
  <xacro:property name="camera_mount_z_offset"         value="${0*cm2m}"/>

  <xacro:property name="oakd_lite_x_offset"             value="${5.294026*cm2m}"/>
  <xacro:property name="oakd_lite_y_offset"             value="${0*cm2m}"/>
  <xacro:property name="oakd_lite_z_offset"             value="${9.25385*cm2m}"/>

  <!-- Sensor pose for laser (rplidar), depth_camera (oakd_lite), and camera_mount -->
  <!-- From linorobot2_description 2wd_properties.urdf.xacro -->

 <!--  For linorobot2 sensor xacros , MUST match mtbc1.urdf.xacro xacro:name
  <xacro:property name="laser_pose">
    <origin xyz="0.12 0 0.33" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="depth_sensor_pose">
    <origin xyz="0.14 0.0 0.045" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="camera_bracket_pose">
    <origin xyz="0.14 0.0 0.045" rpy="0 0 0"/>
  </xacro:property>
  -->
    
  <!-- For Turtlebot4 sensor xacros , MUST match xacro mtbc1.urdf.xacro xacro:name-->
  <xacro:rplidar name="rplidar" parent_link="base_link">
    <origin xyz="${rplidar_x_offset} ${rplidar_y_offset} ${rplidar_z_offset + shelf_zoff}"
            rpy="0 0 0"/>
  </xacro:rplidar>
  
  <xacro:camera_bracket name="oakd_camera_bracket" parent_link="base_link">
    <origin xyz="${camera_mount_x_offset} ${camera_mount_y_offset} ${camera_mount_z_offset + shelf_zoff}"/>
  </xacro:camera_bracket>

  <xacro:oakd name="oakd" model="lite" parent_link="oakd_camera_bracket">
    <origin xyz="${oakd_lite_x_offset} ${oakd_lite_y_offset} ${oakd_lite_z_offset}"/>
  </xacro:oakd>

</robot>