<?xml version="1.0"?>
<!-- Based on Turtlebot4 model, create1 base defined in mtbc1_base.urdf.xacro which is called in 2wdc1.urdf.xacro -->
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:include filename="(find mtbc1_description)/urdf/sensors_shelf.urdf.xacro"/>
<xacro:include filename="(find mtbc1_description)/urdf/rplidar.urdf.xacro"/>
<xacro:include filename="(find mtbc1_description)/urdf/camera_bracket.urdf.xacro"/>
<xacro:include filename="(find mtbc1_description)/urdf/imu.urdf.xacro"/>

<!-- Mechanical properties -->
  <xacro:property name="rplidar_x_offset"              value="${0.393584*cm2m}"/>
  <xacro:property name="rplidar_y_offset"              value="${0*cm2m}"/>
  <xacro:property name="rplidar_z_offset"              value="${7.529272*cm2m}"/>

  <xacro:property name="camera_mount_x_offset"         value="${-9*cm2m}"/>
  <xacro:property name="camera_mount_y_offset"         value="${0*cm2m}"/>
  <xacro:property name="camera_mount_z_offset"         value="${2.914772*cm2m}"/>

  <xacro:property name="oakd_lite_x_offset"             value="${5.294026*cm2m}"/>
  <xacro:property name="oakd_lite_y_offset"             value="${0*cm2m}"/>
  <xacro:property name="oakd_lite_z_offset"             value="${9.25385*cm2m}"/>

  <!-- Turtlebot4 sensor definitions with gazebo parameters deleted-->

  <xacro:rplidar name="rplidar" parent_link="base_link">
    <origin xyz="${rplidar_x_offset} ${rplidar_y_offset} ${rplidar_z_offset + base_link_z_offset}"
            rpy="0 0 ${pi/2}"/>
  </xacro:rplidar>
  
  <xacro:camera_bracket name="oakd_camera_bracket" parent_link="base_link">
    <origin xyz="${camera_mount_x_offset} ${camera_mount_y_offset} ${camera_mount_z_offset + base_link_z_offset}"/>
  </xacro:camera_bracket>

  <xacro:oakd model="lite" parent_link="oakd_camera_bracket">
    <origin xyz="${oakd_lite_x_offset} ${oakd_lite_y_offset} ${oakd_lite_z_offset}"/>
  </xacro:oakd>
</robot>